import BigNumber from 'bignumber.js';

/**
 * Status of a confidential settlement
 */
export enum ConfidentialSettlementStatus {
  /**
   * Settlement is pending affirmations
   */
  Pending = 'Pending',
  /**
   * Settlement has been executed successfully
   */
  Executed = 'Executed',
  /**
   * Settlement has been rejected by a mediator
   */
  Rejected = 'Rejected',
}

/**
 * Represents a leg in a confidential settlement
 */
export interface ConfidentialSettlementLeg {
  /**
   * Index of this leg in the settlement
   */
  legIndex: BigNumber;
  /**
   * The confidential asset ID being transferred
   */
  assetId: BigNumber;
  /**
   * Sender's confidential account public key
   */
  sender: string;
  /**
   * Receiver's confidential account public key
   */
  receiver: string;
  /**
   * Mediator encryption key (if any)
   */
  mediator?: string;
}

/**
 * Represents the affirmation status of a leg
 */
export interface ConfidentialLegAffirmationStatus {
  /**
   * Whether the sender has affirmed
   */
  senderAffirmed: boolean;
  /**
   * Whether the receiver has affirmed
   */
  receiverAffirmed: boolean;
  /**
   * Whether the mediator has affirmed (if applicable)
   */
  mediatorAffirmed?: boolean;
}

/**
 * Details of a confidential settlement
 */
export interface ConfidentialSettlementDetails {
  /**
   * Settlement ID
   */
  id: BigNumber;
  /**
   * Current status of the settlement
   */
  status: ConfidentialSettlementStatus;
  /**
   * Optional memo attached to the settlement
   */
  memo?: string;
  /**
   * Block number when the settlement was created
   */
  createdAt: BigNumber;
  /**
   * Legs in this settlement
   */
  legs: ConfidentialSettlementLeg[];
}

/**
 * Parameters for creating a confidential settlement
 */
export interface CreateConfidentialSettlementParams {
  /**
   * The settlement proof generated by the DART WASM library.
   * Can be a hex string (with 0x prefix) or raw Uint8Array bytes.
   */
  proof: string | Uint8Array;
}

/**
 * Parameters for affirming a confidential settlement leg
 */
export interface AffirmConfidentialSettlementParams {
  /**
   * The affirmation proof generated by the DART WASM library.
   * Can be a hex string (with 0x prefix) or raw Uint8Array bytes.
   */
  proof: string | Uint8Array;
}
