import BigNumber from 'bignumber.js';

import { Identity } from '~/internal';

/**
 * Represents a DART confidential asset's details
 */
export interface ConfidentialAssetDetails {
  /**
   * The asset ID (u32)
   */
  id: BigNumber;
  /**
   * Name of the confidential asset
   */
  name: string;
  /**
   * Symbol/ticker of the confidential asset
   */
  symbol: string;
  /**
   * Number of decimals for the asset
   */
  decimals: number;
  /**
   * Identity that owns this confidential asset
   */
  owner: Identity;
  /**
   * Custom data associated with the asset
   */
  data: string;
  /**
   * Total supply of the asset (if known)
   */
  totalSupply: BigNumber;
}

/**
 * Represents the auditors and mediators for a confidential asset
 */
export interface ConfidentialAssetAuditors {
  /**
   * List of auditor encryption public keys
   */
  auditors: string[];
  /**
   * List of mediator encryption public keys
   */
  mediators: string[];
}

/**
 * Parameters for creating a confidential asset
 */
export interface CreateConfidentialAssetParams {
  /**
   * Name of the asset
   */
  name: string;
  /**
   * Symbol/ticker of the asset (max 12 characters)
   */
  symbol: string;
  /**
   * Number of decimals (0-18)
   */
  decimals: number;
  /**
   * Auditor encryption public keys
   */
  auditors: string[];
  /**
   * Mediator encryption public keys
   */
  mediators?: string[];
  /**
   * Optional custom data to attach to the asset
   */
  data?: string;
}

/**
 * Parameters for minting confidential assets
 */
export interface MintConfidentialAssetParams {
  /**
   * The minting proof generated by the DART WASM library
   */
  proof: string;
}
