import { ConfidentialSettlement } from '~/api/entities/ConfidentialSettlement';
import { CreateConfidentialSettlementParams } from '~/api/entities/ConfidentialSettlement/types';
import { createConfidentialSettlement } from '~/api/procedures/createConfidentialSettlement';
import { Context, PolymeshError } from '~/internal';
import { ErrorCode, ProcedureMethod } from '~/types';
import { createProcedureMethod } from '~/utils/internal';

/**
 * Handles all Confidential Settlement related functionality
 */
export class ConfidentialSettlements {
  private readonly context: Context;

  /**
   * @hidden
   */
  constructor(context: Context) {
    this.context = context;

    this.createSettlement = createProcedureMethod(
      {
        getProcedureAndArgs: args => [createConfidentialSettlement, args],
      },
      context
    );
  }

  /**
   * Create a new Confidential Settlement
   *
   * @note This requires a settlement proof generated by the DART WASM library
   * @note Unlike regular settlements, confidential settlements do not use venues
   */
  public createSettlement: ProcedureMethod<
    CreateConfidentialSettlementParams,
    ConfidentialSettlement
  >;

  /**
   * Retrieve a Confidential Settlement by its ID
   *
   * @param args.id - The settlement reference ID
   */
  public async getSettlement(args: { id: string }): Promise<ConfidentialSettlement> {
    const { context } = this;

    const settlement = new ConfidentialSettlement(args, context);

    const exists = await settlement.exists();

    if (!exists) {
      throw new PolymeshError({
        code: ErrorCode.DataUnavailable,
        message: `Confidential Settlement with ID "${args.id}" does not exist`,
      });
    }

    return settlement;
  }
}
