import { ConfidentialAccount } from '~/api/entities/ConfidentialAccount';
import { registerConfidentialAccounts } from '~/api/procedures/registerConfidentialAccounts';
import { Context, Identity, PolymeshError } from '~/internal';
import { ErrorCode, ProcedureMethod } from '~/types';
import { identityIdToString } from '~/utils/conversion';
import { createProcedureMethod } from '~/utils/internal';

/**
 * Parameters for registering confidential accounts
 */
export interface RegisterConfidentialAccountsParams {
  /**
   * The registration proof generated by the DART WASM library.
   * Can be a hex string (with 0x prefix) or raw Uint8Array bytes.
   */
  proof: string | Uint8Array;
}

/**
 * Handles all Confidential Account related functionality
 */
export class ConfidentialAccounts {
  private readonly context: Context;

  /**
   * @hidden
   */
  constructor(context: Context) {
    this.context = context;

    this.registerConfidentialAccounts = createProcedureMethod(
      {
        getProcedureAndArgs: args => [registerConfidentialAccounts, args],
      },
      context
    );
  }

  /**
   * Register new Confidential Accounts
   *
   * @note This requires a proof generated by the DART WASM library
   */
  public registerConfidentialAccounts: ProcedureMethod<
    RegisterConfidentialAccountsParams,
    ConfidentialAccount[]
  >;

  /**
   * Retrieve a Confidential Account by its public key
   *
   * @param args.publicKey - The DART account public key (hex string)
   */
  public async getConfidentialAccount(args: { publicKey: string }): Promise<ConfidentialAccount> {
    const { context } = this;

    const account = new ConfidentialAccount(args, context);

    const exists = await account.exists();

    if (!exists) {
      throw new PolymeshError({
        code: ErrorCode.DataUnavailable,
        message: `Confidential Account with public key "${args.publicKey}" does not exist`,
      });
    }

    return account;
  }

  /**
   * Get all Confidential Accounts owned by an identity
   *
   * @param args.did - The identity DID
   */
  public async getConfidentialAccountsByIdentity(args: {
    did: string;
  }): Promise<ConfidentialAccount[]> {
    const {
      context: {
        polymeshApi: { query },
      },
      context,
    } = this;

    const { did } = args;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const confidentialAssets = (query as any).confidentialAssets;
    if (!confidentialAssets) {
      throw new PolymeshError({
        code: ErrorCode.DataUnavailable,
        message: 'Confidential assets module is not available on this chain',
      });
    }

    const entries = await confidentialAssets.didAccounts.entries(did);

    return entries.map(
      ([
        {
          args: [, rawPublicKey],
        },
      ]: [{ args: [unknown, { toString(): string }] }, unknown]) =>
        new ConfidentialAccount({ publicKey: rawPublicKey.toString() }, context)
    );
  }

  /**
   * Get the identity that owns a confidential account
   *
   * @param args.publicKey - The DART account public key (hex string)
   * @returns The identity if the account exists, null otherwise
   */
  public async getIdentityFromConfidentialAccount(args: {
    publicKey: string;
  }): Promise<Identity | null> {
    const {
      context: {
        polymeshApi: { query },
      },
      context,
    } = this;

    const { publicKey } = args;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const confidentialAssets = (query as any).confidentialAssets;
    if (!confidentialAssets) {
      throw new PolymeshError({
        code: ErrorCode.DataUnavailable,
        message: 'Confidential assets module is not available on this chain',
      });
    }

    const rawDid = await confidentialAssets.accountDid(publicKey);

    if (rawDid.isNone) {
      return null;
    }

    return new Identity({ did: identityIdToString(rawDid.unwrap()) }, context);
  }

  /**
   * Get the encryption key associated with a confidential account
   *
   * @param args.publicKey - The DART account public key (hex string)
   * @returns The encryption key if set, null otherwise
   */
  public async getEncryptionKey(args: { publicKey: string }): Promise<string | null> {
    const {
      context: {
        polymeshApi: { query },
      },
    } = this;

    const { publicKey } = args;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const confidentialAssets = (query as any).confidentialAssets;
    if (!confidentialAssets) {
      throw new PolymeshError({
        code: ErrorCode.DataUnavailable,
        message: 'Confidential assets module is not available on this chain',
      });
    }

    const rawKey = await confidentialAssets.accountEncryptionKey(publicKey);

    if (rawKey.isNone) {
      return null;
    }

    return rawKey.unwrap().toString();
  }
}
