name: Run Integration Tests
on:
  workflow_dispatch:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      CI: true
    steps:
      - uses: actions/checkout@v7
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v7
        with:
          node-version: '22.x'
      - name: install dependencies
        run: yarn install --immutable
      - name: test
        run: yarn test:integration
